version: "3.3"

services:
  google-fonts-proxy:
    image: cloverzrg/google-fonts-proxy
    container_name: google-fonts-proxy
    environment:
      TZ: Asia/Shanghai
      DOMAIN: jeongen.com
    restart: always
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.google-fonts-proxy.rule=Host(`fonts.jeongen.com`)||Host(`fonts-static.jeongen.com`)"
      - "traefik.http.services.google-fonts-proxy.loadbalancer.server.port=80"

networks:
  traefik-net:
    external:
      name: traefik-net
